apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customers-tomcat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rromannissen/appmod-enablement.git
    targetRevision: main
    path: customers-tomcat-k8s/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: retail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
